AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket and CloudFront for jarvis public frontend

Parameters:
  HostName:
    Type: String
    Description: host name for the application.
  ACMCertificate:
    Type: String
    Description: The ACM arn SSL certificate for the specified domain.
  CachePolicyId:
    Type: String
    Description: Managed cache policy
  PublicAPIGatewayDomainName:
    Type: String
    Description: public api gateway domain name.
  PartnersUrls:
    Type: String
    Description: partners' urls that are allowed to embed the frontend page. Input in the following format "<source> <source> ..."

Resources:
  FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub jarvis-front-end-public-${AWS::Region}-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html

  AppAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref FrontEndBucket

  FrontEndBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: AppAccessIdentity
    Properties:
      Bucket: !Ref FrontEndBucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: jarvis-public
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${FrontEndBucket}/*"
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${AppAccessIdentity}

  WebAppDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: AppAccessIdentity
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${FrontEndBucket}.s3.amazonaws.com
            Id: WebAppS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${AppAccessIdentity}
            OriginPath: /dist
          - DomainName: !Sub ${FrontEndBucket}.s3.amazonaws.com
            Id: Static
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${AppAccessIdentity}
          - Id: RedirectApi
            DomainName: !Ref PublicAPIGatewayDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
          - Id: ApiWhitelabel
            DomainName: !Ref PublicAPIGatewayDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: "true"
        DefaultRootObject: index.html
        Aliases:
          - !Ref HostName
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: Static
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: !Ref CachePolicyId
            PathPattern: "/static/*"
            ResponseHeadersPolicyId: !Ref WebAppSecurityHeaders
          - AllowedMethods:
              - GET
              - HEAD
            SmoothStreaming: false
            CachePolicyId: !Ref CachePolicyId
            PathPattern: "/api/v1/whitelabel*"
            TargetOriginId: ApiWhitelabel
            ViewerProtocolPolicy: redirect-to-https
            OriginRequestPolicyId: !Ref WebAppOriginRequest
            ResponseHeadersPolicyId: !Ref WebAppSecurityHeaders
          - AllowedMethods:
              - GET
              - OPTIONS
              - DELETE
              - PATCH
              - POST
              - PUT
              - HEAD
            SmoothStreaming: false
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            PathPattern: "/api/*"
            TargetOriginId: RedirectApi
            ViewerProtocolPolicy: redirect-to-https
            OriginRequestPolicyId: !Ref WebAppOriginRequest
            ResponseHeadersPolicyId: !Ref WebAppSecurityHeaders
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: WebAppS3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref CachePolicyId
          ResponseHeadersPolicyId: !Ref WebAppSecurityHeaders
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html

  WebAppOriginRequest:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: JarvisPublic
        CookiesConfig:
          CookieBehavior: whitelist
          Cookies:
            - "__utmz"
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - "Referer"
            - "User-Agent"
            - "g-recaptcha-response"
        QueryStringsConfig:
          QueryStringBehavior: all

  WebAppSecurityHeaders:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Comment: Policy to add security headers to response
        Name: JarvisPublicSecurityHeaders
        CustomHeadersConfig:
          Items:
            - Header: X-Robots-Tag
              Override: true
              Value: index
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            ContentSecurityPolicy: !Sub "frame-ancestors ${PartnersUrls};"
            Override: true
          ContentTypeOptions:
            Override: true
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: strict-origin-when-cross-origin
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true
            Preload: false
          XSSProtection:
            ModeBlock: true
            Override: true
            Protection: true